name: altea
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  add_2_calendar: ^2.1.0
  another_flushbar: ^1.10.24
  auto_size_text_pk: ^3.0.0
  camera: 0.9.4+14
  clipboard: ^0.1.3
  cloud_firestore: 3.1.6
  connectivity_plus: ^2.2.1
  cross_connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  expandable_page_view: ^1.0.7
  extended_image: ^4.1.0
  faker_dart: ^0.1.2
  file_picker: ^4.0.0
  firebase_analytics: ^9.1.1
  # firebase_analytics_web: ^0.3.0+1
  firebase_core: 1.11.0
  firebase_crashlytics: ^2.5.2 
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  flutter_ameno_ipsum: ^1.0.1
  flutter_breadcrumb: ^1.0.1
  # flutter_foreground_plugin: ^0.8.0
  flutter_foreground_task: ^3.5.5
  flutter_spinkit: ^5.0.0
  flutter_typeahead: ^3.2.0
  # flutter_webrtc: ^0.6.5  use for latest phase altea, will upgrade to test with new one 0.7.1
  # flutter_webrtc: ^0.7.1
  flutter_webrtc: ^0.8.3
  flutter_widget_from_html_core: ^0.6.1+4
  fluttertoast: ^8.0.8
  get: ^4.1.4
  google_fonts: 2.1.0
  http: ^0.13.3
  image_downloader: ^0.31.0
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  lint: ^1.5.3
  loading_overlay: ^0.3.0
  mime: ^1.0.0
  # onesignal_flutter: ^3.2.0
  pinput: ^1.2.0
  responsive_builder: ^0.4.1
  responsive_framework: ^0.1.4
  screen_recorder: ^0.0.2
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  timer_count_down: ^2.2.0
  universal_html: ^2.0.8
  url_launcher: ^6.0.9
  url_strategy: ^0.2.0
  webview_flutter: ^2.0.10
  path_provider: ^2.0.4
  flutter_masked_text2: ^0.9.1


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  # import_sorter: ^4.6.0

flutter:
  assets:
    - assets/
  uses-material-design: true
